apiVersion: 1

deleteDatasources:
  - name: PostgreSQL
    orgId: 1

datasources:
  - uid: PostgreSQL
    name: PostgreSQL
    type: grafana-postgresql-datasource
    access: proxy
    url: db:5432
    database: $POSTGRES_DB
    user: $POSTGRES_USER
    isDefault: true
    editable: true
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
